name: cms_duckdb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - python-duckdb=0.7.1
  - numpy=1.24.3
  - pandas=2.0.1
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - jupyterlab=3.6.3
  - notebook=6.5.4
